version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    labels:
    - 'traefik.enable=true'
    - 'traefik.port=80'
    - 'traefik.backend=gamtrac-prisma'
    - 'traefik.docker.network=reverseproxy'
    - 'traefik.frontentd.rule=Host:prisma.gamtrac.cndb.biocad.ru'
    networks:
    - internal
    - reverseproxy
    environment:
      PRISMA_CONFIG: |
        port: 80
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            database: postgres
            schema: public
            user: postgres
            password: ''
            ssl: false
            rawAccess: false
            port: '5432'
            migrations: false